"""empty message

Revision ID: 716ca80edf30
Revises:
Create Date: 2024-11-23 21:03:44.768139

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "716ca80edf30"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "t_user",
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("first_name", sa.String(length=256), nullable=False),
        sa.Column("last_name", sa.String(length=256), nullable=False),
        sa.Column("hashed_password", sa.String(length=256), nullable=False),
        sa.Column("role", sa.String(length=256), nullable=True),
        sa.Column("link_cv", sa.String(length=256), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_t_user_id"), "t_user", ["id"], unique=False)
    op.create_table(
        "t_team",
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon_url", sa.String(length=256), nullable=True),
        sa.Column("captain_id", sa.Integer(), nullable=False),
        sa.Column("is_looking_for_members", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["captain_id"],
            ["t_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_index(op.f("ix_t_team_id"), "t_team", ["id"], unique=False)
    op.create_table(
        "t_user_tag",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["t_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_t_user_tag_id"), "t_user_tag", ["id"], unique=False)
    op.create_table(
        "t_request",
        sa.Column("request_team_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("sent_by_team", sa.Boolean(), nullable=False),
        sa.Column("is_ok", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["request_team_id"],
            ["t_team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["t_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_t_request_id"), "t_request", ["id"], unique=False)
    op.create_table(
        "t_team_tag",
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("user_tag_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["t_team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_tag_id"],
            ["t_user_tag.id"],
        ),
        sa.PrimaryKeyConstraint("team_id", "user_tag_id"),
    )
    op.create_table(
        "t_team_user",
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_name", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["t_team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["t_user.id"],
        ),
        sa.PrimaryKeyConstraint("team_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("t_team_user")
    op.drop_table("t_team_tag")
    op.drop_index(op.f("ix_t_request_id"), table_name="t_request")
    op.drop_table("t_request")
    op.drop_index(op.f("ix_t_user_tag_id"), table_name="t_user_tag")
    op.drop_table("t_user_tag")
    op.drop_index(op.f("ix_t_team_id"), table_name="t_team")
    op.drop_table("t_team")
    op.drop_index(op.f("ix_t_user_id"), table_name="t_user")
    op.drop_table("t_user")
    # ### end Alembic commands ###
