version: '3.8'

services:
  user_and_teams_service:
    build:
      dockerfile: ../Dockerfile
    working_dir: /tests
    command: pytest -v -s --postgresql-host=user_and_teams_service_postgresql --postgresql-password=admin --postgresql-user=admin --postgresql-dbname=postgres
    tty: true
    stdin_open: true
    environment:
      PYTHONPATH: /app
      SECURITY_KEY: "709cb22f047a59f492c4d6407e627240e2272bda11ab791c16fb4f4661f7285a95ba6efbc1bbf762cddcc3710a1487f4a3242f21b2d9cd751b3154a452c5a286"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: user_and_teams_service_postgresql
      POSTGRES_PORT: 5432
      POSTGRES_NAME: postgres
    depends_on:
      - "user_and_teams_service_postgresql"

  user_and_teams_service_postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
