name: containerized testing
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --tag backend
        working-directory: ./services/user_and_teams_service

      - name: Save Docker image
        run: docker save backend -o backend.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: backend-image
          path: backend.tar

  testing:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: backend
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-image

      - name: Load Docker image
        run: docker load -i backend.tar

      - name: Start testing
        run: make run-tests
        working-directory: ./services/user_and_teams_service
